FROM php:8.4-fpm-alpine

ENV APP_ENV=test

WORKDIR /app/src

RUN apk add --no-cache \
        bash \
        git \
        unzip \
        zip \
        libzip-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        libssh2 \
        libssh2-dev \
        supervisor \
        postgresql-dev \
        rabbitmq-c-dev \
        autoconf \
        make \
        gcc \
        g++ \
        musl-dev \
        linux-headers \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_pgsql gd zip \
    && pecl install xdebug amqp ssh2 \
    && docker-php-ext-enable xdebug amqp ssh2

COPY ./app /app
COPY ./app/config/php/test/xdebug.ini /usr/local/etc/php/conf.d/
COPY ./app/config/supervisor/php-fpm.conf /etc/supervisor/conf.d/
COPY ./docs /opt/docs

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
    && composer install --optimize-autoloader --prefer-dist --no-interaction --ignore-platform-req=ext-swoole --optimize-autoloader